<?php

// ─── .htaccess helpers ────────────────────────────────────────────────────────

function yai_htaccess_has_rule() {
    if ( !file_exists( YAI_HTACCESS ) ) return false;
    return strpos( file_get_contents( YAI_HTACCESS ), YAI_HTACCESS_MARKER ) !== false;
}

function yai_htaccess_add_rule() {
    if ( yai_htaccess_has_rule() ) return true;
    if ( !file_exists( YAI_HTACCESS ) || !is_writable( YAI_HTACCESS ) ) return false;

    $content = file_get_contents( YAI_HTACCESS );
    $insert  = YAI_HTACCESS_RULE . "\n\n";

    if ( preg_match( '/^RewriteCond\s/m', $content ) ) {
        $content = preg_replace( '/^(RewriteCond\s)/m', $insert . '$1', $content, 1 );
    } elseif ( preg_match( '/^RewriteRule\s/m', $content ) ) {
        $content = preg_replace( '/^(RewriteRule\s)/m', $insert . '$1', $content, 1 );
    } else {
        return false;
    }

    return file_put_contents( YAI_HTACCESS, $content ) !== false;
}

function yai_htaccess_remove_rule() {
    if ( !file_exists( YAI_HTACCESS ) || !yai_htaccess_has_rule() ) return true;
    $content = file_get_contents( YAI_HTACCESS );
    $content = preg_replace( '/\n?' . preg_quote( YAI_HTACCESS_MARKER, '/' ) . '.*?' . preg_quote( '# END YAI-root', '/' ) . '\n*/s', "\n", $content );
    return file_put_contents( YAI_HTACCESS, $content ) !== false;
}

// ─── index.php helpers ────────────────────────────────────────────────────────
// Primary mechanism: rewrite the YOURLS root index.php so that visiting / loads
// yourls-loader.php (and thus the plugin system). Works regardless of Apache
// AllowOverride settings, Nginx, or reverse-proxy configurations.

function yai_index_is_custom() {
    if ( !file_exists( YAI_INDEX ) ) return false;
    return strpos( file_get_contents( YAI_INDEX ), YAI_INDEX_MARKER ) !== false;
}

function yai_index_apply() {
    if ( yai_index_is_custom() ) return true;

    $dir_writable  = is_writable( dirname( YAI_INDEX ) );
    $file_writable = file_exists( YAI_INDEX ) && is_writable( YAI_INDEX );
    if ( !$dir_writable && !$file_writable ) return false;

    if ( file_exists( YAI_INDEX ) && !file_exists( YAI_INDEX_BACKUP ) ) {
        copy( YAI_INDEX, YAI_INDEX_BACKUP );
    }

    $content = "<?php\n" . YAI_INDEX_MARKER . "\n"
        . "/* Root URL managed by YOURLS Alternative Index plugin.\n"
        . "   Original backed up at index.php.yai-bak — do not edit this file manually. */\n"
        . "require_once __DIR__ . '/yourls-loader.php';\n";

    return file_put_contents( YAI_INDEX, $content ) !== false;
}

function yai_index_restore() {
    $dir_writable  = is_writable( dirname( YAI_INDEX ) );
    $file_writable = file_exists( YAI_INDEX ) && is_writable( YAI_INDEX );
    if ( !$dir_writable && !$file_writable ) return false;

    if ( file_exists( YAI_INDEX_BACKUP ) ) {
        $ok = copy( YAI_INDEX_BACKUP, YAI_INDEX );
        if ( $ok ) unlink( YAI_INDEX_BACKUP );
        return $ok;
    }

    $content = "<?php\nheader( 'HTTP/1.0 403 Forbidden' );\ndie( 'This page is not accessible directly.' );\n";
    return file_put_contents( YAI_INDEX, $content ) !== false;
}
